# Generated by Django 4.2.14 on 2024-07-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disp_name',
            field=models.CharField(max_length=256, verbose_name='disp_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='username'),
        ),
    ]
